const CONSTANTS = {
  RESTORE_MERCHANT_REQUESTED: 'RESTORE_MERCHANT_REQUESTED',
  RESTORE_MERCHANT_SUCCEEDED: 'RESTORE_MERCHANT_SUCCEEDED',
  RESTORE_MERCHANT_FAILED: 'RESTORE_MERCHANT_FAILED',

  LOGIN_REQUESTED: 'LOGIN_REQUESTED',
  LOGIN_SUCCEEDED: 'LOGIN_SUCCEEDED',
  LOGIN_FAILED: 'LOGIN_FAILED',

  GET_ADDRESSE_REQUESTED: 'GET_ADDRESSE_REQUESTED',
  GET_ADDRESSE_SUCCEEDED: 'GET_ADDRESSE_SUCCEEDED',
  GET_ADDRESSE_FAILED: 'GET_ADDRESSE_FAILED',


  CHANGE_SELECTED_MENU_REQUESTED: 'CHANGE_SELECTED_MENU_REQUESTED',
  CHANGE_SELECTED_MENU_SUCCEEDED: 'CHANGE_SELECTED_MENU_SUCCEEDED',
  CHANGE_SELECTED_MENU_FAILED: 'CHANGE_SELECTED_MENU_FAILED',

  GET_PROFILE_DATA_REQUESTED: 'GET_PROFILE_DATA_REQUESTED',
  GET_PROFILE_DATA_SUCCEEDED: 'GET_PROFILE_DATA_SUCCEEDED',
  GET_PROFILE_DATA_FAILED: 'GET_PROFILE_DATA_FAILED',

  ADD_OR_REMOVE_FAV_REQUESTED: 'ADD_OR_REMOVE_FAV_REQUESTED',
  ADD_OR_REMOVE_FAV_SUCCEEDED: 'ADD_OR_REMOVE_FAV_SUCCEEDED',
  ADD_OR_REMOVE_FAV_FAILED: 'ADD_OR_REMOVE_FAV_FAILED',

  GET_ALL_FAVS_REQUESTED: 'GET_ALL_FAVS_REQUESTED',
  GET_ALL_FAVS_SUCCEEDED: 'GET_ALL_FAVS_SUCCEEDED',
  GET_ALL_FAVS_FAILED: 'GET_ALL_FAVS_FAILED',

  SAVE_ADDRESS_REQUESTED: 'SAVE_ADDRESS_REQUESTED',
  SAVE_ADDRESS_SUCCEEDED: 'SAVE_ADDRESS_SUCCEEDED',
  SAVE_ADDRESS_FAILED: 'SAVE_ADDRESS_FAILED',


  CHANGE_LANG_REQUESTED: 'CHANGE_LANG_REQUESTED',
  CHANGE_LANG_SUCCEEDED: 'CHANGE_LANG_SUCCEEDED',
  CHANGE_LANG_FAILED: 'CHANGE_LANG_FAILED',


  LOGIN_MERCHANTS_REQUESTED: 'LOGIN_MERCHANTS_REQUESTED',
  LOGIN_MERCHANTS_SUCCEEDED: 'LOGIN_MERCHANTS_SUCCEEDED',
  LOGIN_MERCHANTS_FAILED: 'LOGIN_MERCHANTS_FAILED',

  GET_ITEMS_REQUESTED: 'GET_ITEMS_REQUESTED',
  GET_ITEMS_SUCCEEDED: 'GET_ITEMS_SUCCEEDED',
  GET_ITEMS_FAILED: 'GET_ITEMS_FAILED',

  GET_MENU_CATEGORIES_REQUESTED: 'GET_MENU_CATEGORIES_REQUESTED',
  GET_MENU_CATEGORIES_SUCCEEDED: 'GET_MENU_CATEGORIES_SUCCEEDED',
  GET_MENU_CATEGORIES_FAILED: 'GET_MENU_CATEGORIES_FAILED',

  GET_ITEMS_BY_CATEGORY_REQUESTED: 'GET_ITEMS_BY_CATEGORY_REQUESTED',
  GET_ITEMS_BY_CATEGORY_SUCCEEDED: 'GET_ITEMS_BY_CATEGORY_SUCCEEDED',
  GET_ITEMS_BY_CATEGORY_FAILED: 'GET_ITEMS_BY_CATEGORY_FAILED',


  SHOW_HIDE_FOOTER_REQUESTED: 'SHOW_HIDE_FOOTER_REQUESTED',
  SHOW_HIDE_FOOTER_SUCCEEDED: 'SHOW_HIDE_FOOTER_SUCCEEDED',
  SHOW_HIDE_FOOTER_FAILED: 'SHOW_HIDE_FOOTER_FAILED',


  GO_TO_CATEGORY_REQUESTED: 'GO_TO_CATEGORY_REQUESTED',
  GO_TO_CATEGORY_SUCCEEDED: 'GO_TO_CATEGORY_SUCCEEDED',
  GO_TO_CATEGORY_FAILED: 'GO_TO_CATEGORY_FAILED',


  ADD_TO_CART_REQUESTED: 'ADD_TO_CART_REQUESTED',
  ADD_TO_CART_SUCCEEDED: 'ADD_TO_CART_SUCCEEDED',
  ADD_TO_CART_FAILED: 'ADD_TO_CART_FAILED',


  EDIT_CART_ITEM_REQUESTED: 'EDIT_CART_ITEM_REQUESTED',
  EDIT_CART_ITEM_SUCCEEDED: 'EDIT_CART_ITEM_SUCCEEDED',
  EDIT_CART_ITEM_FAILED: 'EDIT_CART_ITEM_FAILED',


  GET_CART_REQUESTED: 'GET_CART_REQUESTED',
  GET_CART_SUCCEEDED: 'GET_CART_SUCCEEDED',
  GET_CART_FAILED: 'GET_CART_FAILED',

  REMOVE_FROM_CART_REQUESTED: 'REMOVE_FROM_CART_REQUESTED',
  REMOVE_FROM_CART_SUCCEEDED: 'REMOVE_FROM_CART_SUCCEEDED',
  REMOVE_FROM_CART_FAILED: 'REMOVE_FROM_CART_FAILED',

  GET_MY_ORDERS_REQUESTED: 'GET_MY_ORDERS_REQUESTED',
  GET_MY_ORDERS_SUCCEEDED: 'GET_MY_ORDERS_SUCCEEDED',
  GET_MY_ORDERS_FAILED: 'GET_MY_ORDERS_FAILED',


  LOGOUT_REQUESTED: 'LOGOUT_REQUESTED',
  LOGOUT_SUCCEEDED: 'LOGOUT_SUCCEEDED',
  LOGOUT_FAILED: 'LOGOUT_FAILED',

  GET_NOTIFICATION_REQUESTED: 'GET_NOTIFICATION_REQUESTED',
  GET_NOTIFICATION_SUCCEEDED: 'GET_NOTIFICATION_SUCCEEDED',
  GET_NOTIFICATION_FAILED: 'GET_NOTIFICATION_FAILED',
};

export default CONSTANTS;