// This file was generated by importTranslations.js
const strings = {
  quantity: {
    ar: 'الكمية :',
    en: 'Quantity :'

  },
  jd: {
    ar: 'د.أ',
    en: 'JD'
  },
  options: {
    ar: 'الاضافات',
    en: 'Options'
  },
  most_selling: {
    ar: 'الأكثر مبيعا',
    en: 'Most Selling'
  },
  save: {
    ar: 'وفر',
    en: 'save'
  },
  home: {
    ar: 'الرئيسية',
    en: 'Home'
  },
  offers: {
    ar: 'العروض',
    en: 'Offers'
  },
  menu: {
    ar: 'القائمة',
    en: 'Menu'
  },
  orders: {
    ar: 'طلباتي',
    en: 'Orders'
  },
  account: {
    ar: 'حسابي',
    en: 'Account'
  },
  recent_orders: {
    ar: 'طلباتي',
    en: 'Recent Orders'
  },
  no_orders: {
    ar: 'لا يوجد اي طلبات حاليا',
    en: 'You haven’t ordered yet'
  },
  start_order: {
    ar: 'اطلب الان >',
    en: 'Start Ordering >'
  },
  cart_items: {
    ar: 'محتويات السلة:',
    en: 'Cart Items:'
  },
  checkout: {
    ar: 'اتمام الطلب',
    en: 'Checkout'
  },
  continue_shopping: {
    ar: 'استمر بالتسوق',
    en: 'Continue Shopping'
  },
  empty_cart: {
    ar: 'سلة الشراء فارغة',
    en: 'Your shopping cart is empty'
  },
  start_shopping: {
    ar: 'ابدا التسوق الان',
    en: 'Start shopping now'
  },
  search_here: {
    ar: 'ابحث عن المنتجات هنا',
    en: 'Search Items Here'
  },
  quantity_1: {
    ar: 'الكمية',
    en: 'Quantity'
  },
  price: {
    ar: 'السعر',
    en: 'Price'
  },
  notes: {
    ar: 'ملاحظات',
    en: 'Notes'
  },
  back: {
    ar: 'رجوع',
    en: 'Back'
  },
  add_to_cart: {
    ar: 'اضف الى السلة',
    en: 'Add to cart'
  },
  items: {
    ar: 'المنتجات',
    en: 'Items'
  },
  no_offers: {
    ar: 'لم يتم العثور على عروض',
    en: 'No Offers Found'
  },
  no_result: {
    ar: 'لم يتم العثور على نتائج',
    en: 'No Results Found'
  },
  note: {
    ar: 'ملاحظة',
    en: 'Note'
  },
  added_to_cart: {
    ar: 'تم إضافة المنتج بنجاح',
    en: 'Item Added Successfully'
  },
  view_cart: {
    ar: 'شاهد السلة',
    en: 'View Cart'
  },
  login_title: {
    ar: 'يرجى ادخال رقم هاتفك للاستمرار',
    en: 'Please enter your Mobile Number to continue'
  },
  send: {
    ar: 'إرسال',
    en: 'Send'
  },
  mobile_number: {
    ar: 'رقم الهاتف',
    en: 'Mobile Number'
  },
  resend_otp: {
    ar: 'اعد ارسال الرمز',
    en: 'Resend OTP'
  },
  otp: {
    ar: 'الرمز',
    en: 'otp'
  },
  next: {
    ar: 'التالي',
    en: 'next'
  },
  deliveryFees: {
    ar: 'رسوم التوصيل',
    en: 'Delivery Fees'
  },
  tax: {
    ar: 'الضريبة',
    en: 'Tax'
  },
  deliveryAddress: {
    ar: 'عنوان التوصيل',
    en: 'Delivery Address'
  },
  change: {
    ar: 'تغيير',
    en: 'Change'
  },
  no_address: {
    ar: 'لا يوجد لديك عنوان',
    en: "You don't have any more address"
  },
  add_new_address: {
    ar: 'اضف عنوان جديد >',
    en: 'Add A New Address >'
  },
  paymentMethod: {
    ar: 'طريقة الدفع',
    en: 'Payment Method'
  },
  cash: {
    ar: 'الدفع عند الاستلام',
    en: 'Cash on Delivery'
  },
  credit_card: {
    ar: 'البطاقة الائتمانية',
    en: 'Credit Card'
  },
  soon: {
    ar: 'قريبا',
    en: 'Coming Soon'
  },
  Confirm_Order: {
    ar: 'اتمام الطلب',
    en: 'Confirm Order'
  },
  my_addresses: {
    ar: 'عناويني',
    en: 'My Addresses'
  },
  ad_addresses: {
    ar: 'اضف عنوان',
    en: 'Add Address'
  },
  address_name: {
    ar: 'اسم الموقع (منزل,عمل)',
    en: '"Address Name (Home,Office..)"'
  },
  address_name_1: {
    ar: 'اسم العنوان',
    en: 'Address Name'
  },
  street_address: {
    ar: 'اسم الشارع',
    en: 'Street Address'
  },
  apartment_number: {
    ar: 'رقم العمارة/الطابق',
    en: 'Apartment/Floor Number (Optional)'
  },
  city: {
    ar: 'المدينة',
    en: 'City'
  },
  city_state: {
    ar: 'الحي',
    en: 'state'
  },
  select_on_map: {
    ar: 'اختر على الخريطة',
    en: 'Select On Map'
  },
  area: {
    ar: 'المنطقة',
    en: 'Area'
  },
  added_address_successfuly: {
    ar: 'تم اضافة العنوان بنجاح',
    en: 'Added address successfuly'
  },
  map: {
    ar: 'الخريطة',
    en: 'Map'
  },
  apply: {
    ar: 'موافق',
    en: 'Apply'
  },
  please_choose_address: {
    ar: 'يرجى اختيار العنوان',
    en: 'Please choose your address'
  },
  SubTotal: {
    ar: 'المجموع الفرعي',
    en: 'Sub Total'
  },
  total: {
    ar: 'المجموع الكلي',
    en: 'Total Price'
  },
  something_worng: {
    ar: 'حصل خطا ما يرجى المحاولة لاحقا',
    en: 'something went worng, please try agian later'
  },
  order_success: {
    ar: 'تم انشاء طلبك بنجاح',
    en: 'Your Order Has Been Placed Successfully.'
  },
  Continue: {
    ar: 'استمرار',
    en: 'Continue'
  },
  track_order: {
    ar: 'تتبع طلباتك',
    en: 'Track Your Orders'
  },
  pending: {
    ar: 'قيد التحضير',
    en: 'PENDING'
  },
  order_history: {
    ar: 'تاريخ الطلبات',
    en: 'Order History'
  },
  OrderSummary: {
    ar: 'ملخص الطلب',
    en: 'Order Summary'
  },
  change_address_success: {
    ar: 'تم تغيير العنوان بنجاح',
    en: 'Your location has been changed successfuly'
  },
  done: {
    ar: 'تم',
    en: 'Done'
  },
  enter_your_name: {
    ar: 'ادخل اسمك',
    en: 'Enter your name'
  },
  enter_your_email: {
    ar: 'ادخل ايميلك',
    en: 'Enter your email'
  },
  male: {
    ar: 'ذكر',
    en: 'Male'
  },
  female: {
    ar: 'أنثى',
    en: 'Female'
  },
  facebook: {
    ar: 'الاستمرار باستخدام الفيسبوك',
    en: 'Continue Using Facebook'
  },
  skip: {
    ar: 'تخطى',
    en: 'Skip'
  },
  notifications: {
    ar: 'الاشعارات',
    en: 'Notifications'
  },
  fav: {
    ar: 'مفضلتي',
    en: 'Favorites'
  },
  Building: {
    ar: 'رقم العمارة',
    en: 'Building #'
  },
  floor: {
    ar: 'رقم الطابق (اختياري)',
    en: 'Floor # (Optional)'
  },
  filter: {
    ar: 'تصنيف',
    en: 'Filter'
  },
  remove_all: {
    ar: 'حذف الكل',
    en: 'Remove All'
  },
  price_range: {
    ar: 'نطاق السعر',
    en: 'Price Range'
  },
  apply_filters: {
    ar: 'فلترة',
    en: 'Apply Filters'
  },
  notifications: {
    ar: 'الإشعارات',
    en: 'Notifications'
  },
  categories: {
    ar: 'الأقسام',
    en: 'Categories'
  },
  edit_or_remove: {
    ar: 'هل ترغب بحذف او تعديل العنوان؟',
    en: 'Do you want Edit or Delete the Address?'
  },
  edit: {
    ar: 'تعديل',
    en: 'Edit'
  },
  delete: {
    ar: 'حذف',
    en: 'Delete'
  },
  cancel: {
    ar: 'الغاء',
    en: 'Cancel'
  },
  edit_addresses: {
    ar: 'تعديل العنوان',
    en: 'Edit Address'
  },
  saving: {
    ar: 'حفظ',
    en: 'Save'
  },
  apply_active: {
    ar: 'تفعيل',
    en: 'Apply'
  },
  CouponCode: {
    ar: 'الكوبون',
    en: 'Coupon Code'
  },
  discount: {
    ar: 'الخصم',
    en: 'Discount'
  },
  logout: {
    ar: 'تسجيل الخروج',
    en: 'Logout'
  },
  are_you_sure_logout: {
    ar: 'هل أنت متأكد من تسجيل الخروج؟',
    en: 'Are you sure logout?'
  },
  yes_logout: {
    ar: 'خروج',
    en: 'Logout'
  },
  wait_logout: {
    ar: 'يرجى الانتظار يتم الان تسجيل الخروج',
    en: 'Please wait while logout'
  },
  whatsup: {
    ar: 'تواصل معنا عن طريق الوتس اب',
    en: 'WhatsApp us'
  },
  terms: {
    ar: 'الشروط و القوانين',
    en: 'Terms and conditions'
  },
  privacy: {
    ar: 'حقوق الملكية',
    en: 'Privacy policy'
  },
  rate: {
    ar: 'قيم التطبيق',
    en: 'Rate our app'
  },
  change_lang: {
    ar: 'تغيير اللغة',
    en: 'Change language'
  },
  from_bob: {
    ar: 'من بوب',
    en: 'From BoB'
  },
  processing: {
    ar: 'قيد التحضير',
    en: 'under process'
  },
  delivering: {
    ar: 'قيد التوصيل',
    en: 'delivering'
  },
  delivered: {
    ar: 'تم التوصيل',
    en: 'delivered'
  },
  rejected: {
    ar: 'ملغي',
    en: 'rejected'
  },
  edit_address: {
    ar: 'تم تعديل العنوان بنجاح',
    en: 'Edit Address Successfuly',
  },
  add_address: {
    ar: 'تم اضافة العنوان بنجاح',
    en: 'Add Address Successfuly',
  },
  Edit_Profile: {
    ar: 'تعديل الحساب',
    en: 'Edit Profile '
  },
  name: {
    ar: 'الاسم',
    en: 'Name'
  },
  enter_name: {
    ar: 'ادخل اسمك',
    en: 'Enter your name'
  },
  gender: {
    ar: 'الجنس',
    en: 'Gender'
  },
  choose_gender: {
    ar: 'اختر الجنس',
    en: 'Choose gender'
  },
  email: {
    ar: 'الايميل',
    en: 'Email'
  },
  phone: {
    ar: 'رقم الهاتف',
    en: 'Phone Number'
  },
  enter_phone: {
    ar: 'ادخل رقم الهاتف',
    en: 'Enter Phone Number'
  },
  birthday: {
    ar: 'تاريخ الميلاد',
    en: 'Date Of Birthday '
  },
  enter_birthday: {
    ar: 'ادخل تاريخ الميلاد',
    en: 'Enter Date Of Birthday'
  },
  choose_gender: {
    ar: 'اختر الجنس',
    en: 'Choose gender'
  },
  close: {
    ar: 'إلغاء',
    en: 'Close'
  },
  choose_date: {
    ar: 'اختر التاريخ',
    en: 'Choose Date'
  },
  edit_success: {
    ar: 'تم التعديل بنجاح',
    en: 'Edit Successfuly'
  },
  otp_text: {
    ar: 'لقد أرسلنا رمز OTP إلى رقم هاتفك المحمول ، يرجى إدخاله',
    en: 'We have sent an OTP code to your mobile number, please enter it'
  },
  login: {
    ar: 'تسجيل الدخول',
    en: 'Login'
  },
  view_all: {
    ar: 'مشاهدة الكل',
    en: 'View All'
  },
  today: {
    ar: 'اليوم',
    en: 'Today'
  },
  order_time: {
    ar: 'اختر وقت التوصييل',
    en: 'Choose your order time'
  },
  tommorow: {
    ar: 'غدا',
    en: 'Tommorow'
  },
  all_brands: {
    ar: 'جميع البراندات',
    en: 'ALL BRANDS'
  },
  all_cats: {
    ar: 'جميع الاصناف',
    en: 'ALL Categoires'
  },
  shop_now: {
    ar: 'تسوق الآن',
    en: 'Shop now'
  },
  change_image: {
    ar: 'تغيير الصورة الشخصية',
    en: 'Change profile picture'
  },
  camera: {
    ar: 'كاميرا',
    en: 'Camera'
  },
  gallary: {
    ar: 'الاستوديو',
    en: 'Gallary'
  },
  rejected: {
    ar: 'ملغي',
    en: 'Canceled'
  },
  rate_item: {
    ar: 'قييم',
    en: 'Rate'
  },
  Review: {
    ar: 'تقييم',
    en: 'Review'
  },
  review_text: {
    ar: 'اضف تقييمك للمنتج',
    en: 'add your review for the product '
  },
  submit: {
    ar: 'ارسل',
    en: 'submit'
  },
  Reviews: {
    ar: 'التقييمات',
    en: 'Reviews'
  },
  card_number: {
    ar: 'رقم البطاقة',
    en: 'Card number'
  },
  holder_name: {
    ar: 'اسم حامل البطاقة',
    en: 'Holder name'
  },
  exp_date: {
    ar: 'تاريخ الانتهاء',
    en: 'Exp Date'
  },
  pay: {
    ar: 'الدفع',
    en: 'Pay'
  },
  search_products: {
    ar: 'ابحث عن المنتجات',
    en: 'Search for Products'
  },
  loyalty: {
    ar: 'نقاط الولاء',
    en: 'Loyalty Coins'
  },
  points: {
    ar: 'النقاط',
    en: 'Points'
  },
  total_price: {
    ar: 'المجموع الكلي',
    en: 'Total Price'
  },
  see_all: {
    ar: 'مشاهدة الكل',
    en: 'See All'
  },
  brands: {
    ar: 'البراندات',
    en: 'Brands'
  },
  indoor: {
    ar: 'داخل المحل',
    en: 'Indoor'
  },
  delivery: {
    ar: 'توصيل',
    en: 'Delivery'
  },
  table_number: {
    ar: 'رقم الطاولة',
    en: 'Table Number'
  },
  please_choose_table_number: {
    ar: 'يرجى اختيار رقم الطاولة',
    en: 'please choose table number'
  },
  user_support_credit: {
    ar: 'الرجاء استخدام بطاقة دفع مدعومة',
    en: 'Please use supported credit card'
  },
  insert_number: {
    ar: 'الرجاء ادخال الرقم المكون من ',
    en: 'Please insert the number contians '
  },
  digits: {
    ar: 'خانة',
    en: 'digits'
  },
  correct_card_number: {
    ar: 'الرجاء ادخال رقم بطاقة صحيح',
    en: 'Please insert correct credit card number'
  },
  card_name: {
    ar: 'الرجاء ادخال اسم حامل البطاقة',
    en: 'Please insert the name of creidt card'
  },
  expir_date: {
    ar: 'الرجاء ادخال تاريخ انتهاء صحيح',
    en: 'Please insert correct Exp date'
  },
  wrong_cvv: {
    ar: 'CVV غير صحيح',
    en: 'incorrect CVV'
  },

  please_enable_location: {
    ar: 'يرجى تفعيل خاصية المواقع ثم الضغط على جرب مرة اخرى',
    en: 'Please enable location and press try again'
  },
  try_again: {
    ar: 'جرب مرة اخرى',
    en: 'Try again'
  },
  most_orders: {
    ar: 'الاكثر طلبا',
    en: 'Most orders'
  },
  specifications: {
    ar: 'المواصفات',
    en: 'Specifications'
  },
  options_1: {
    ar: 'الخيارات',
    en: 'Options'
  },
  rating: {
    ar: 'التقييم',
    en: 'Ratings'
  },
  no_Reviews: {
    ar: 'لا يوجد تقييمات لهذا المنتج',
    en: 'No Reviews for this Item'
  },
  newly_arrive: {
    ar: 'وصل حديثا',
    en: 'Recently arrived'
  },
  StockOut: {
    ar: 'عذزا غير متوفر حاليا',
    en: 'Sorry, Item Out Of Stock'
  },
  choose_option: {
    ar: 'يرجى اختيار الاضافات قبل اضافة المنتج',
    en: 'Please choose option before add the item'
  },
  ask_share: {
    ar: 'يطلب منك مشاركة الطلب مع',
    en: 'asked you to share the order with'
  },
  ask_share2: {
    ar: 'فقط قم باضافة الطلبات الى',
    en: 'Just add your product to'
  },
  ask_share3: {
    ar: 'سلة المشتريات',
    en: 'shopping cart'
  },
  from_you: {
    ar: "قمت باضافتها",
    en: 'From You '
  },
  From_Others: {
    ar: 'من الاخرين',
    en: 'From Others'
  },
  go_to_shop: {
    ar: 'تسوق المزيد',
    en: 'Go to Shop More'
  },
  Add: {
    ar: 'اضافة',
    en: 'Add'
  },
  date: {
    ar: 'التاريخ',
    en: 'Date'
  },
  time: {
    ar: 'الوقت',
    en: 'Time'
  },
  no_item_share: {
    ar: 'لم يقم اي احد باضافة منتجات الى السلة',
    en: 'No One Add Items To Your Cart '
  },
  share_with_others: {
    ar: 'شارك مع الاخرين',
    en: 'Share With Others'
  },
  optional: {
    ar: 'اختياري',
    en: 'Optional'
  },
  upload_your_image: {
    ar: 'ارفع الصورة',
    en: 'Upload Your Image'
  },
  edit_profile: {
    ar: 'تعديل الحساب',
    en: 'Edit Profile'
  },
  new: {
    ar: 'جديد',
    en: 'New'
  },
  about_us: {
    ar: 'عنّا',
    en: 'About Us'
  },
  language: {
    ar: 'اللغة',
    en: 'Language'
  },
  facebook_1: {
    ar: 'فايسبوك',
    en: 'Facbook'
  },
  insta: {
    ar: 'انستقرام',
    en: 'Instagram'
  },
  whatsapp: {
    ar: 'واتس اب',
    en: 'WhatsApp'
  },
  youtube: {
    ar: 'يوتيوب',
    en: 'Youtube'
  },
  branches: {
    ar: 'المواقع',
    en: 'Locations'
  },
  more: {
    ar: 'المزيد',
    en: 'More'
  },
  add_to_order: {
    ar: 'أضف إلى الطلب',
    en: 'Add To Order'
  },
  added_to_order: {
    ar: 'تم اضافته الى الطلب بنجاح',
    en: 'Added Successfully to Order'
  },
  view_order: {
    ar: 'شاهد الطلب',
    en: 'View Order'
  },
  order_items: {
    ar: 'محتويات الطلب:',
    en: 'Order Items:'
  },
  empty_order: {
    ar: 'لم يتم اضافة اي منتج للطلب',
    en: 'Your shopping order is empty'
  },
  item_added: {
    ar: 'تم اضافة المنتج بنجاح',
    en: 'Item added successfully'
  },
  tax_note: {
    ar: 'الاسعار لا تشمل ضريبة المبيعات والخدمات',
    en: 'All prices are Tax and Service exclusive.'
  },
  please_enter_your_name: {
    ar: 'يرجى كتابة اسمك لاتمام الطلب',
    en: 'Please enter your name to complete the order'
  }
}
export default strings;